server:
  port: 8081

spring:
  application:
    name: order-service
  boot:
    admin:
      client: # Spring Boot Admin 监控服务器端地址
        url: http://localhost:9000
  cloud:
    nacos:
      server-addr: 192.168.58.100:8847
      discovery: # 这些即使不配也有默认值
        username: nacos
        password: nacos
        namespace: public