spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_demo?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 9
  redis:
    database: 2
    host: localhost
    port: 6379
    password: 12345
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
  boot:
    admin:
      client:
        url:
          - http://localhost:9001


server:
  port: 8080


management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    path: D:\\log


