server:
  port: 8081

spring:
  application:
    name: shiro-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_demo?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456