spring:
  application:
    name: client-authcode
  boot:
    admin:
      client:
        url:
          - http://localhost:9001
server:
  port: 8082
  servlet:
    context-path: /client-authcode


security:
  oauth2:
    client:
      client-id: code-client
      client-secret: code-secret-8888
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key
        key-value: dev
    authorization:
      check-token-access: http://localhost:8080/oauth/check_token

management:
  endpoints:
    web:
      exposure:
        include: all